# -*- coding: utf-8 -*-
"""SA_contour3_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DYB0oFJZL1Fg6oUi8WSVMAQXktqKEecf
"""

import torch
import torch.nn as nn

N_POINTS = 100

class ResidualContourModel(nn.Module):

    def __init__(self):

        super().__init__()

        self.backbone = nn.Sequential(

            nn.Linear(400,512),
            nn.BatchNorm1d(512),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(512,256),
            nn.BatchNorm1d(256),
            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(256,200)
        )

        self.shortcut = nn.Linear(
            400,
            200
        )

    def forward(
        self,
        prev_pts,
        future_pts
    ):

        batch = prev_pts.size(0)

        x = torch.cat(
            [
                prev_pts.view(batch,-1),
                future_pts.view(batch,-1)
            ],
            dim=1
        )

        out = (
            self.backbone(x)
            +
            self.shortcut(x)
        )

        return out.view(batch,100,2)