# -*- coding: utf-8 -*-
"""SA_contour1_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nUEZPvLBA9Q79_ufcm5HnEzRd8wmgiWI
"""

import torch
import torch.nn as nn
from scipy.interpolate import interp1d
import numpy as np

N_POINTS = 100

class ContourModel1_CNN(nn.Module):

    def __init__(self):
        super().__init__()

        self.net = nn.Sequential(

            nn.Conv1d(4, 64, kernel_size=5, padding=2),
            nn.BatchNorm1d(64),
            nn.GELU(),

            nn.Conv1d(64, 128, kernel_size=5, padding=2),
            nn.BatchNorm1d(128),
            nn.GELU(),

            nn.Conv1d(128,128, kernel_size=5, padding=2),
            nn.BatchNorm1d(128),
            nn.GELU(),

            nn.Conv1d(128, 64, kernel_size=3, padding=1),
            nn.BatchNorm1d(64),
            nn.GELU(),

            nn.Conv1d(64, 2, kernel_size=1)
        )

    def forward(self, prev_pts, future_pts):

        x = torch.cat(
            [prev_pts, future_pts],
            dim=-1
        )

        x = x.permute(0, 2, 1)

        x = self.net(x)

        return x.permute(0, 2, 1)

# ==========================================================
# NORMALIZATION
# ==========================================================

def normalize_triplet(
    prev_pts,
    future_pts,
    gt_pts
):

    all_pts = np.concatenate([
        prev_pts,
        future_pts
    ], axis=0)

    mean = all_pts.mean(axis=0)
    std = all_pts.std(axis=0) + 1e-6

    prev_pts = (prev_pts - mean) / std
    future_pts = (future_pts - mean) / std
    gt_pts = (gt_pts - mean) / std

    return prev_pts, future_pts, gt_pts, mean, std

# ==========================================================
# RESAMPLE
# ==========================================================

def resample(pts, n=N_POINTS):

    try:

        pts = np.array(pts, dtype=np.float32)

        if pts.ndim != 2:
            return None

        if pts.shape[0] == 2:
            pts = pts.T

        if pts.shape[1] != 2:
            return None

        if len(pts) < 2:
            return None

        diffs = np.diff(pts, axis=0)

        arc = np.concatenate(
            [
            [0],
            np.cumsum(np.sqrt((diffs ** 2).sum(1)))
        ])

        if arc[-1] == 0:
            return None

        arc /= arc[-1]

        _, idx = np.unique(
            arc,
            return_index=True
        )

        arc = arc[idx]
        pts = pts[idx]

        if len(arc) < 2:
            return None

        t = np.linspace(0, 1, n)

        fx = interp1d(
            arc,
            pts[:, 0],
            kind='linear',
            fill_value='extrapolate'
        )

        fy = interp1d(
            arc,
            pts[:, 1],
            kind='linear',
            fill_value='extrapolate'
        )

        pts = np.stack([
            fx(t),
            fy(t)
        ], axis=1)

        return pts.astype(np.float32)

    except Exception as e:
        print("RESAMPLE ERROR:", e)
        raise

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print(f"\n DEVICE: {DEVICE}")